name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Dockerfile with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy config .

      - name: Scan Terraform code with Checkov
        run: |
          pip install checkov
          checkov -d terraform

      - name: Build Docker image
        run: |
          docker build -t demo-app:latest .
          trivy image demo-app:latest

  zap-scan:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - name: Run Node.js app container
        run: |
          docker build -t zap-demo-app .
          docker run -d -p 3000:3000 --name zap-app zap-demo-app
          sleep 10  # wait for the app to fully start

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
