name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Dockerfile with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy config .

      - name: Scan Terraform code with Checkov
        run: |
          pip install checkov
          checkov -d terraform

      - name: Build Docker image
        run: |
          docker build -t demo-app:latest .
          trivy image demo-app:latest
